### ISSUE TITLE
The Update URL is Not Correct 

### ISSUE THREAD

**Issue by dembeck** [magicoflolis/Userscript-Plus#1]
In the script the updateURL and downloadURL are set to:
`https://github.com/magicoflolis/Userscript-Plus/raw/master/dist/show-site-all-userjs.user.js`

That URI 404s and I think they should be set to:
`https://github.com/magicoflolis/Userscript-Plus/raw/master/dist/magic-userjsplus.user.js`

Possible fix would be to make a file called 'show-site-all-userjs.user.js' so that updates work, and have that file point to 'magic-userjsplus.user.js' for future updates and downloads.

**Comment by magicoflolis** [comment]
Apologies for not address this sooner, I have migrated it to my own /dist/magic-userjs.gf.user.js & /dist/magic-userjs.user.js.

**Note**
06/08/2021
As of **version 2.3.12** of the UserScript builds hosted on GitHub, they are currently broken and should **not** be installed for use just yet, I'm currently restructuring script assets over to this GitHub.

The UserScript hosted on GreasyFork still works and have a working Firefox and Chrome release.
