### ISSUE TITLE
There is a problem with the page display

### ISSUE THREAD

**Issue by sunshuanglong20010414** [magicoflolis/Userscript-Plus#10]
![chrome_l83f34CpLJ](https://user-images.githubusercontent.com/111521534/185434447-7943f673-d3cc-41e9-b4e3-5bbd67df344e.png)
The page shows that 3 scripts were found to apply to the current page, but no scripts were found.

**Comment by magicoflolis** [comment]
Possible bug in UserJS or GreasyFork/Sleazyfork

Tampermonkey was used to load script.

![image](https://user-images.githubusercontent.com/10752602/191388137-1e6839ba-0378-4866-a2f3-ff1f2001872c.png)
