### ISSUE TITLE
How did this happen?

### ISSUE THREAD

**Issue by sunshuanglong20010414** [magicoflolis/Userscript-Plus#11]
https://user-images.githubusercontent.com/111521534/185441511-b8615967-c7e5-4d35-839c-e7da0ba9ac38.mp4

Please watch the screen video I recorded.

**Comment by magicoflolis** [comment]
https://github.com/magicoflolis/Userscript-Plus/releases

**v2.4.13**

* Added ability to customize width
* This *may* resolve issue
* In addition, original authors used iVue for list/table styling, which has led to this stretching bug.
