### ISSUE TITLE
显示不全

### ISSUE THREAD

**Issue by Snake1997** [magicoflolis/Userscript-Plus#13]
我的电脑端显示不全 只显示安装前面的名称显示不出来

**Comment by Snake1997** [comment]
<img width="665" alt="屏幕截图 2022-08-29 110251" src="https://user-images.githubusercontent.com/112364059/187114772-533f2217-4c97-4e82-98b3-6eee0b131e2c.png">

**Comment by magicoflolis** [comment]
https://github.com/magicoflolis/Userscript-Plus/releases

**v2.4.13**

* Added ability to customize width
* This *may* resolve issue
