### ISSUE TITLE
The over extension while using YouTube

### ISSUE THREAD

**Issue by waytooconfident** [magicoflolis/Userscript-Plus#20]
The UI overextends itself while using YouTube, causing users unable to read what scripts are capable as the appendix shows.
![擷取](https://user-images.githubusercontent.com/91171214/189409127-2440a4f5-c8a4-4655-8566-d4982ff57da8.PNG)

**Comment by magicoflolis** [comment]
https://github.com/magicoflolis/Userscript-Plus/releases

**v2.4.13**

* Added ability to customize width
* This *may* resolve issue
