### ISSUE TITLE
Option keeps getting stretched out of bounds

### ISSUE THREAD

**Issue by dr860724** [magicoflolis/Userscript-Plus#21]
![2022-09-20](https://user-images.githubusercontent.com/66559671/191285310-c7f7e7c6-bab4-458c-ac91-431594e389ca.png)
The option keeps getting stretched out of bounds and can't see what the title of the script is

https://user-images.githubusercontent.com/66559671/191287701-c55c0c97-b3ff-4c95-82e5-7edf200ba019.mp4

**Comment by magicoflolis** [comment]
https://github.com/magicoflolis/Userscript-Plus/releases

**v2.4.13**

* Added ability to customize width
* This *may* resolve issue
