### ISSUE TITLE
no icon displayed

### ISSUE THREAD

**Issue by gabri25ele** [magicoflolis/Userscript-Plus#23]
Someone can explain me why the Userscript not display any icon of the script, and the **Userscript Legacy works** perfectly.

I tried in Firefox and in Vivaldi (last version of course), with Violentmonkey and Tampermonkley.
I tried also with a clean profile (with only monkey added).

**Comment by magicoflolis** [comment]
Try updating the script and if this issue persists then which websites does it not appear on?

**Comment by gabri25ele** [comment]
> 

still not work after update
in all (every) sites (example google.com)
