### ISSUE TITLE
[Feature Request] Sorting, Bigger UI and Better Filtering

### ISSUE THREAD

**Issue by SedapnyaTidur** [magicoflolis/Userscript-Plus#25]
Unfortunately, the way websites keep changing day by day - unable to sort to latest (by date) is something really dissappointing and a bigger UI (fullscreen) would be better - there is so little usefulness to make it half the screen - unnecessary scrolling for example, especially when there are many results. For filtering, a more precise would be good e.g.   `www.youtube.com` won't work for `m.youtube.com` but `*.youtube.com` might.

**Comment by SedapnyaTidur** [comment]
Filtering other languages does not work for recent updates. Used to work though. Able to filter just ASCII or ISO-5589-1/Latin-1 would be wonderful.

**Comment by i486** [comment]
I've been using the Firefox add-on version of Userscript-Plus for a while now and I love it! However, I recently tried the updated script version of Userscript-Plus and was a bit disappointed to see that the sorting options were missing. 

I was wondering if there's any chance you could add the sorting options back into the updated script version of Userscript-Plus? I think it would greatly improve the experience of using the script. Plus, I bet I'm not the only one who would appreciate this feature!

Cheers

**Comment by magicoflolis** [comment]
* Added ability to sort list. In addition, list has been converted to Table element [v5.11.19](https://github.com/magicoflolis/Userscript-Plus/releases/tag/5.11.19)

I will be closing this issue.

**Comment by i486** [comment]
Looks nice and sort is working great!

I have one other request.

```
Total installs
Ratings
Created date
```
I suspect you wouldn't want to add these sorting options to the script as default. But it would be great if you add it as toggle indicator option in the scripts settings menu.

Thanks!
