### ISSUE TITLE
grey screen 

### ISSUE THREAD

**Issue by supperzaki** [magicoflolis/Userscript-Plus#31]
whenever I enter youtube the youtube  page turns grey for half a minute or 15 seconds and turns to its normal color tried disable all tweaks did not solve the problem just when I turn this tweak off everything went normal

**Comment by EscalatorMan** [comment]
I had the same problem. Had to remove it.

**Comment by magicoflolis** [comment]
What web browser and userscript manager are you using?

**Comment by supperzaki** [comment]
Google  Chrome >>>>Web Browser
Violeymonkey >>>>>UserScript manager

**Comment by supperzaki** [comment]
> 

Google Chrome >>>>Web Browser
Violeymonkey >>>>>UserScript manager
