### ISSUE TITLE
err

### ISSUE THREAD

**Issue by lhj1618GitHub** [magicoflolis/Userscript-Plus#36]
<html>
<body>
<mujs-row class="error" style="display: flex; gap: 10px; flex-direction: column; background: rgb(52, 58, 69); color: rgb(209, 207, 204);">TypeError: Cannot convert object to primitive value<a class="magicuserjs-urls" href="https://greasyfork.org/scripts/by-site/douyin.com.json" target="_blank" rel="noopener" style="background: rgb(52, 58, 69); color: rgb(209, 207, 204);">https://greasyfork.org/scripts/by-site/douyin.com.json</a><a class="magicuserjs-urls" href="https://sleazyfork.org/scripts/by-site/douyin.com.json" target="_blank" rel="noopener" style="background: rgb(52, 58, 69); color: rgb(209, 207, 204);">https://sleazyfork.org/scripts/by-site/douyin.com.json</a><a class="magicuserjs-urls" href="https://openuserjs.org/?q=douyin.com" target="_blank" rel="noopener" style="background: rgb(52, 58, 69); color: rgb(209, 207, 204);">https://openuserjs.org/?q=douyin.com</a><a class="magicuserjs-urls" href="https://github.com/search?l=JavaScript&amp;o=desc&amp;q=%22==UserScript==%22+douyin.com" target="_blank" rel="noopener" style="background: rgb(52, 58, 69); color: rgb(209, 207, 204);">https://github.com/search?l=JavaScript&amp;o=desc&amp;q="==UserScript=="+douyin.com</a><a class="magicuserjs-urls" href="https://gist.github.com/search?l=JavaScript&amp;o=desc&amp;q=%22==UserScript==%22+douyin.com" target="_blank" rel="noopener" style="background: rgb(52, 58, 69); color: rgb(209, 207, 204);">https://gist.github.com/search?l=JavaScript&amp;o=desc&amp;q="==UserScript=="+douyin.com</a></mujs-row><table style="width: -webkit-fill-available; background: rgb(52, 58, 69); color: rgb(209, 207, 204);"><thead style="background: rgb(52, 58, 69); color: rgb(209, 207, 204); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><tr style="background: rgb(52, 58, 69); color: rgb(209, 207, 204);"><th class="mujs-header-name mujs-pointer" style="user-select: none !important; border-bottom: 1px solid rgb(43, 47, 49); position: sticky; top: 0px; background: rgb(52, 58, 69); color: rgb(209, 207, 204); cursor: pointer !important; width: 885.5px;">Name</th><th class="mujs-pointer" style="user-select: none !important; border-bottom: 1px solid rgb(43, 47, 49); position: sticky; top: 0px; background: rgb(52, 58, 69); color: rgb(209, 207, 204); cursor: pointer !important;">Created by</th><th class="mujs-pointer" style="user-select: none !important; border-bottom: 1px solid rgb(43, 47, 49); position: sticky; top: 0px; background: rgb(52, 58, 69); color: rgb(209, 207, 204); cursor: pointer !important;">日常安装</th><th class="mujs-pointer" style="user-select: none !important; border-bottom: 1px solid rgb(43, 47, 49); position: sticky; top: 0px; background: rgb(52, 58, 69); color: rgb(209, 207, 204); cursor: pointer !important;">最后更新</th><th style="user-select: none !important; border-bottom: 1px solid rgb(43, 47, 49); position: sticky; top: 0px; background: rgb(52, 58, 69); color: rgb(209, 207, 204);">安装</th></tr></thead><tbody style="background: rgb(52, 58, 69); color: rgb(209, 207, 204); font-family: Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><tr class="frame " style="background: rgb(52, 58, 69); color: rgb(209, 207, 204);"><td class="magicuserjs-name" style="border-bottom: 1px solid rgb(43, 47, 49); background: rgb(52, 58, 69); color: rgb(209, 207, 204); display: grid;">
</body>
</html>TypeError: Cannot convert object to primitive value
https://greasyfork.org/scripts/by-site/douyin.com.json
https://sleazyfork.org/scripts/by-site/douyin.com.json
https://openuserjs.org/?q=douyin.com
[https://github.com/search?l=JavaScript&o=desc&q="==UserScript=="+douyin.com](https://github.com/search?l=JavaScript&o=desc&q=%22==UserScript==%22+douyin.com)
[https://gist.github.com/search?l=JavaScript&o=desc&q="==UserScript=="+douyin.com](https://gist.github.com/search?l=JavaScript&o=desc&q=%22==UserScript==%22+douyin.com)

**Comment by magicoflolis** [comment]
> TypeError: Cannot convert object to primitive valuehttps://greasyfork.org/scripts/by-site/douyin.com.jsonhttps://sleazyfork.org/scripts/by-site/douyin.com.jsonhttps://openuserjs.org/?q=douyin.com[https://github.com/search?l=JavaScript&o=desc&q="==UserScript=="+douyin.com](https://github.com/search?l=JavaScript&o=desc&q=%22==UserScript==%22+douyin.com)[https://gist.github.com/search?l=JavaScript&o=desc&q="==UserScript=="+douyin.com](https://gist.github.com/search?l=JavaScript&o=desc&q=%22==UserScript==%22+douyin.com)
> Name	Created by	日常安装	最后更新	安装
> TypeError: Cannot convert object to primitive value https://greasyfork.org/scripts/by-site/douyin.com.json https://sleazyfork.org/scripts/by-site/douyin.com.json https://openuserjs.org/?q=douyin.com [https://github.com/search?l=JavaScript&o=desc&q="==UserScript=="+douyin.com](https://github.com/search?l=JavaScript&o=desc&q=%22==UserScript==%22+douyin.com) [https://gist.github.com/search?l=JavaScript&o=desc&q="==UserScript=="+douyin.com](https://gist.github.com/search?l=JavaScript&o=desc&q=%22==UserScript==%22+douyin.com)

Are you on the latest version? `v5.12.0`? https://github.com/magicoflolis/Userscript-Plus/releases


https://greasyfork.org/en/scripts/421603-magic-userscript-show-site-all-userjs/discussions/194706
