### ISSUE TITLE
Typing my username in the search bar

### ISSUE THREAD

**Issue by Bamboozul** [magicoflolis/Userscript-Plus#37]
Hi,

For some reason, the script is automatically typing my username into the search bar on both Reddit and GitHub.

![Screenshot 2023-09-01 193541](https://github.com/magicoflolis/Userscript-Plus/assets/101983929/6f133169-b119-4a0f-b7f9-f0a3d7364e05)

![Screenshot 2023-09-01 193734](https://github.com/magicoflolis/Userscript-Plus/assets/101983929/fe1566f7-e553-4a94-9dfc-773d4510c95f)

Script Version: 6.0.1
Violentmonkey Version: 2.15.0
Browser: Chrome Version 116.0.5845.141 (Official Build) (64-bit)

**Comment by magicoflolis** [comment]
> Hi,
> 
> For some reason, the script is automatically typing my username into the search bar on both Reddit and GitHub.
> 
> ![Screenshot 2023-09-01 193541](https://user-images.githubusercontent.com/101983929/265092264-6f133169-b119-4a0f-b7f9-f0a3d7364e05.png)
> 
> ![Screenshot 2023-09-01 193734](https://user-images.githubusercontent.com/101983929/265092279-fe1566f7-e553-4a94-9dfc-773d4510c95f.png)
> 
> Script Version: 6.0.1 Violentmonkey Version: 2.15.0 Browser: Chrome Version 116.0.5845.141 (Official Build) (64-bit)

Does this still happen when you disable the script?

From what I recall the script should only auto fill boxes within it's little window

**Comment by Trixarn** [comment]
Same here

**Comment by Bamboozul** [comment]
> Does this still happen when you disable the script?

No, It doesn't happen if I disable the script. And, as Trixarn mentioned, that happens on other websites as well.

**Comment by giaez** [comment]
coming here to report similar issue but already found this.
yeah I also encounter this problem currently. whenever I activate the Magic Userscript+ it autofills my username into the searchbar of most websites (twitter, facebook, reddit, all types of forum sites, etc). problem doesn't occur when the script is disabled.

**Comment by kongyuliuyun** [comment]
so am i

**Comment by zjcxdcq** [comment]
same

**Comment by jfkruuse** [comment]
Yep, and same problem here.

**Comment by YBxbxxz** [comment]
俺也一样

**Comment by Bamboozul** [comment]
Just to let you know, the issue has not been resolved in the recent update.

**Comment by magicoflolis** [comment]
> Just to let you know, the issue has not been resolved in the recent update.

I have finally identified this bug. Your user name was being typed due to Chromes password manager auto filling any `input type="search"` with your saved username & `input type="password"` with your saved password. The userscript injects a password type input. I shall release a fix for this in this next update.

![image](https://github.com/magicoflolis/Userscript-Plus/assets/10752602/4a8f2b56-a74b-4bdf-9556-ced3c23e658c)
