### ISSUE TITLE
网站配置CSP时，脚本无法正确加载

### ISSUE THREAD

**Issue by qixing-jk** [magicoflolis/Userscript-Plus#40]
![Clip_20231128_012029](https://github.com/magicoflolis/Userscript-Plus/assets/125447674/ad66b7d5-f4a2-4f02-aac1-dbe90f5f1ea5)
出现多为google系产品，如 https://bard.google.com/

**Comment by magicoflolis** [comment]
Fixed as of [v6.2.0](https://github.com/magicoflolis/Userscript-Plus/releases/tag/6.2.0)
