### ISSUE TITLE
Errors ("User" or otherwise)

### ISSUE THREAD

**Issue by boognish-rising** [magicoflolis/Userscript-Plus#42]
I've encountered a few possible errors while using your script (which is very good, btw) that I thought I would at least bring to your attention, since you seem committed to maintain a high level of functionality and quality, etc for it.

As indicated, any/all of the errors I encountered could very well either be a result of user error or more probably, unique configurations/hardware differences. Of course, there's also the obvious but always possible conflict with another script or browser extension, but I'll leave that for you to decide and/or whether it is worthy of your time to address.

The first is one I've only encountered on my handset, so it at least affects mobile and more specifically, Kiwi Browser for Android but interestingly, only on my Pixel 8 Pro in Android 14, but it was NOT reproducible using Kiwi Browser on an Android _tablet_ running Android 13, or at least not in the same way (the errors the interface reports are identical but whereas Kiwi on the tablet is "silent" from a global perspective, i.e., no popups or generally being "in your face" about it). 

It's easier to show you.

On a handset running A14, I get:

https://github.com/magicoflolis/Userscript-Plus/assets/76668060/5e61092e-5a7b-4bd5-871c-2a740bd734d4

Whatever the underlying cause (I thought it was toggling "GitHub API" without actually providing it, but it turns out both that and "OpenJS" will throw similar errors), the script's GUI handles them in exactly the same manner, verbatim regardless of the device or Android OS version. So am I right to assume that this is likely something to take up with Kiwi devs? 

This second thing is very minor and almost a non issue, but I'm already here so I figured taking an extra 30s to address wouldn't kill me. Simply put, the output of the GUI for scripts that provide an English translation (title and/or description) in addition to author's native language seem to default to the the author's native tongue rather than the end users'. 

Again it's easier to show you than explain:

https://github.com/magicoflolis/Userscript-Plus/assets/76668060/8c27c4b3-2424-4fd7-ab23-926ec4d6752b

Sorry for my long-winded nature 🤣

Thanks for the excellent script! 

Edit - in hindsight, I should've disabled "OpenJS" & "GitHub API" so the script didn't throw the related errors in the second clip. My apologies for my short-sightedness

**Comment by magicoflolis** [comment]
If this userscript encounters an error it will notify the user through `alert()` function on mobile or when a serious error occurs that would cause the script to not inject itself onto the page.

https://github.com/magicoflolis/Userscript-Plus/blob/a372228a1eb19f754f3574b6c927c1eecc31ff26/src/UserJS/main.js#L52
``` js
const err = (...msg) => {
  console.error(
    '[%cUserJS%c] %cERROR',
    'color: rgb(29, 155, 240);',
    '',
    'color: rgb(249, 24, 128);',
    ...msg
  );
  let alertBrowser = false;
  for (const ex of msg) {
    if (typeof ex === 'object' && 'cause' in ex) {
      alertBrowser = true;
      break;
    }
  }
  if (isMobile || alertBrowser) {
    alert(...msg);
  }
};
```
In addition, you can toggle `Filter out other languages` in the settings to get the translated version of a userscripts name & description. *Don't forget to hit "Save"*

![image](https://github.com/magicoflolis/Userscript-Plus/assets/10752602/73e6e31c-da6d-4d7a-a975-ca36335060d6)

**Comment by boognish-rising** [comment]
Sorry it took me so long to realize you had responded but I appreciate it. I'll go ahead and close this but if you want to reopen it for whatever reason, feel free to do so. Thanks again for the great script!
