### ISSUE TITLE
bls

### ISSUE THREAD

**Issue by benzeghda** [magicoflolis/Userscript-Plus#46]
### **blsspainglobal.com/DZA/bls/vt9101/8df5f6e4?data=TQ3NulznMLxqU6yyzktC9Djcxix0wxoYQ6XG77FhnzbdrtlEq1wdhJoa18AISj3ksUqL%2fdesavzA5tfyqO2gisE%2fX%2f%2bqf2XVZ4OKF%2bvGluP4Fw1OozGPzjKrwQLcWGQG29q7l26reFAzQFnslahyEnsmmWMnp7JBfpx4K1f9zXY%3d**

**Comment by neoOpus** [comment]
fech tnayek?
