### ISSUE TITLE
[bug]: Invalid data received from the server

### ISSUE THREAD

**Issue by neoOpus** [magicoflolis/Userscript-Plus#48]
### Describe the Bug

data.filter is not a function TypeError: data.filter is not a function at forkFN (chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/userscript.html?name=Magic-Userscript%252B-%253A-Show-Site-All-UserJS.user.js&id=fdc1c156-f9ec-4f3d-98ef-5d124c061763:2569:37)

### Steps to reproduce the behavior

I changed the userscript after it failed to check and make this error more user-friendly.
```
const forkFN = async (data) => {
  if (!data || !Array.isArray(data)) {
    MUJS.showError('Invalid data received from the server');
    return;
  }
  
  // Rest of the function...
};
```

### Browser

Edge (latest)

### Type

Userscript

### URL

https://www.google.com/

**Comment by magicoflolis** [comment]
Greasyfork changed some things in the back end of things, I have fixed it. https://github.com/magicoflolis/Userscript-Plus/releases/tag/6.6.2
