### ISSUE TITLE
[bug]: 

### ISSUE THREAD

**Issue by legpuller** [magicoflolis/Userscript-Plus#49]
### Describe the Bug

![1720704886937](https://github.com/magicoflolis/Userscript-Plus/assets/118943235/3f233e39-7915-4015-961c-cf3ac05b248f)
why this happen? how to fix it?

### Steps to reproduce the behavior

![1720704683333](https://github.com/magicoflolis/Userscript-Plus/assets/118943235/17272750-c38c-4186-a5ba-5831eb15c3fb)

### Browser

chrome;edge

### Type

Extension, Userscript

### URL

www.youtube.com

**Comment by magicoflolis** [comment]
Greasyfork changed some things in the back end of things, I have fixed it. https://github.com/magicoflolis/Userscript-Plus/releases/tag/6.6.2
