### ISSUE TITLE
Open icon text automatically slides to the left until it disappears.

### ISSUE THREAD

**Issue by Rainydepp** [magicoflolis/Userscript-Plus#5]
![QQ截图20220321134826](https://user-images.githubusercontent.com/97502622/159210951-d43a9dea-25d6-45b4-b95a-7d9952a0559a.png)

**Comment by Milor123** [comment]
guys, Someone temporal solution for this bug??

**Comment by Nagarafas** [comment]
yup same here

**Comment by Snake1997** [comment]
我也是

**Comment by magicoflolis** [comment]
https://github.com/magicoflolis/Userscript-Plus/releases

**v2.4.13**

* Added ability to customize width
* This *may* resolve issue
