### ISSUE TITLE
[bug]: No UserScripts Loading

### ISSUE THREAD

**Issue by AuZzii-Xssistant** [magicoflolis/Userscript-Plus#56]
### Describe the Bug

I use to be able to see all available UserScripts except for OpenUserJS with a red error, however now no scripts are available for any website. It displays 0 scripts with a blank list.

### Steps to reproduce the behavior

Opening the list at the bottom right corner.

### Browser

Vivaldi

### Type

Userscript

### URL

Https://*

**Comment by magicoflolis** [comment]
Fixed as if v6.7.3 https://github.com/magicoflolis/Userscript-Plus/releases/tag/6.7.3

GreasyFork and SleazyFork changed the response body which broke these engines from working properly.
