### ISSUE TITLE
title bug

### ISSUE THREAD

**Issue by Nagarafas** [magicoflolis/Userscript-Plus#8]
the names and titles of userscripts are going off screen making it imposible to read the names and descriptions of said userscripts
![Screenshot_1](https://user-images.githubusercontent.com/92688719/181775643-c7b09e97-e2af-458c-8406-3138446e63b5.png)
all the titles started going left slowly until they eventually left the screen

edit:  i am on a fresh install of windows 11 latest stable version using opera gx also freshly installed

**Comment by magicoflolis** [comment]
https://github.com/magicoflolis/Userscript-Plus/releases

**v2.4.13**

* Added ability to customize width
* This *may* resolve issue
